id: I763AE617
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3876-final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:52:21.224780'
last_modified: '2022-07-27T11:52:21.224796'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
